language: cpp
script:
  # to enable travis ci, which is using automake 1.11 or so
  - autoreconf -ivf
  - ./configure
  - make 
  - make check
  - sudo make install
  - make maintainer-clean
# cross compile for windows
  - ./configure --host i686-w64-mingw32 --build i686-linux-pc
  - make check
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install libxml2-dev gcc-4.8 g++-4.8 libxml2-utils
# windows cross compiler
  - sudo apt-get -qq install wine mingw-w64 mingw-w64-i686-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ --version
  - automake --version

